version: '3'
services:

  cfssl_api:
    restart: always
    image: serialize/cfssl
    expose:
      - "8888"
    links:
      - cfssl_db:$CFSSL_DB_HOSTNAME
    environment:
      CFSSL_DB_PASSWORD: $CFSSL_DB_PASSWORD
      CFSSL_DB_HOSTNAME: $CFSSL_DB_HOSTNAME
    volumes:
      - cfssl_api_etc:/etc/cfssl/


  cfssl_db:
    restart: always
    image: serialize/postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: $CFSSL_DB_PASSWORD
    volumes:
      - cfssl_db_data:/var/lib/postgresql/data

volumes:
  cfssl_api_etc: {}
  cfssl_db_data: {}  