import os


_basedir = os.path.abspath(os.path.dirname(__file__))

CORS = os.environ.get("LEMUR_CORS") == "True"
debug = os.environ.get("LEMUR_DEBUG") == "True"

SECRET_KEY = repr(os.environ.get('LEMUR_SECRET_KEY','Hrs8kCDNPuT9vtshsSWzlrYW+d+PrAXvg/HwbRE6M3vzSJTTrA/ZEw=='))

LEMUR_TOKEN_SECRET = repr(os.environ.get('LEMUR_TOKEN_SECRET','YVKT6nNHnWRWk28Lra1OPxMvHTqg1ZXvAcO7bkVNSbrEuDQPABM0VQ=='))
LEMUR_ENCRYPTION_KEYS = repr(os.environ.get('LEMUR_ENCRYPTION_KEYS','Ls-qg9j3EMFHyGB_NL0GcQLI6622n9pSyGM_Pu0GdCo='))

LEMUR_WHITELISTED_DOMAINS = []

LEMUR_EMAIL = ''
LEMUR_SECURITY_TEAM_EMAIL = []

LEMUR_DEFAULT_COUNTRY = repr(os.environ.get('LEMUR_DEFAULT_COUNTRY','DE'))
LEMUR_DEFAULT_STATE = repr(os.environ.get('LEMUR_DEFAULT_STATE','BaWue'))
LEMUR_DEFAULT_LOCATION = repr(os.environ.get('LEMUR_DEFAULT_LOCATION','Stuttgart'))
LEMUR_DEFAULT_ORGANIZATION = repr(os.environ.get('LEMUR_DEFAULT_ORGANIZATION','Serialize'))
LEMUR_DEFAULT_ORGANIZATIONAL_UNIT = repr(os.environ.get('LEMUR_DEFAULT_ORGANIZATIONAL_UNIT','IT'))


# MAIL_SERVER : default ‘localhost’
# MAIL_PORT : default 25
# MAIL_USE_TLS : default False
# MAIL_USE_SSL : default False
# MAIL_DEBUG : default app.debug
# MAIL_USERNAME : default None
# MAIL_PASSWORD : default None
# MAIL_DEFAULT_SENDER : default None
# MAIL_MAX_EMAILS : default None
# MAIL_SUPPRESS_SEND : default app.testing
# MAIL_ASCII_ATTACHMENTS : default False


ACTIVE_PROVIDERS = []

METRIC_PROVIDERS = []

LOG_LEVEL = str(os.environ.get('LOG_LEVEL','DEBUG'))
LOG_FILE = str(os.environ.get('LOG_FILE','/var/log/lemur/lemur.log'))

SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:lemur@db:5432/postgres'

CFSSL_URL = 'http://ca:8888'
CFSSL_ROOT = """-----BEGIN CERTIFICATE-----
MIIFrDCCA5SgAwIBAgIUBdydn9cFEmWO5412jhTIWmanEbQwDQYJKoZIhvcNAQEN
BQAwbjELMAkGA1UEBhMCREUxDjAMBgNVBAgTBUJhV3VlMRIwEAYDVQQHEwlTdHV0
dGdhcnQxEjAQBgNVBAoTCVNlcmlhbGl6ZTELMAkGA1UECxMCSVQxGjAYBgNVBAMT
EVNlcmlhbGl6ZSBSb290IENBMB4XDTE5MTExMjAzNTkwMFoXDTI5MTEwOTAzNTkw
MFowbjELMAkGA1UEBhMCREUxDjAMBgNVBAgTBUJhV3VlMRIwEAYDVQQHEwlTdHV0
dGdhcnQxEjAQBgNVBAoTCVNlcmlhbGl6ZTELMAkGA1UECxMCSVQxGjAYBgNVBAMT
EVNlcmlhbGl6ZSBSb290IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
AgEA52V1bq6LuL+g5njZPrruS7seQxEBMkK9n5bWVtx1cvjJPo5uafylxPOqXq9G
yqjzJznJ7A/O9eXC0jielpYz/l6uyyX7k/H+tz7xMcCukh5rPyyW4dILOoWSBCuW
wM3+ZIQhNllRA05NTHNV4pofQJDCJvlk+LbQ8iZPxC3IfC68f7cT3v9tiUhPdYlw
nsWUbL5lRcDcaJyD4mOqtDW0wMbevTglU97qO25uRK+N96Bh+xMLWccIfzoNATgO
cPXN2brYi2YpaE/loOW9bXCy0RamiUvcXvuPLsRAHW725Mxa9RjtMrBdFmeeLzoI
VPjhFuSsRKsyiQEkQnYZj4FeakcrZnINJ7JGTq5fvCt3tcbqahx6NreCbDvCGP4L
6KYtBfEDSTPESVHUHkXFud3PKWIEsE/aPmkWHQKmBJGdEwtfbRPqhZxTeuLdmdTP
27Ei6ToPdwwbQJCAOCR3RWLqF/tQTsRjL34RGTkwZcqUCokYwofkIDufObFPGLJZ
TEXqzhpAckcYedincY3m1TOAU/kiQl9hIZpespe0dTA+cALRSQVzz9f1DxrWZq3z
p8sbSUrrs2yK9HCovrRBJsfCc0LoZZjiPLGo7GgOFcsh1Te6rtvgjAuF3flQNSfR
Q4dmEP4udl7Z9i0SS8b+jzFodngofGrZ3H8UHzJzTz1vFdUCAwEAAaNCMEAwDgYD
VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFO/fuUoCK3Sy
9j7JTzvCtK0b0ZPDMA0GCSqGSIb3DQEBDQUAA4ICAQBRlLef6Mi5q82e3I2BUdkM
Wd1AfRCkvZ8lJ+58rNUTYQvSrp2vHqT5rhQEhqPevpE91bPl4pX0xc/EZj2YLcgI
8H7MWlGp/jsEuQkIPcph3rZbzNS90fcdN4/ZKKZrkSbwtUOALj5zNjUEfqog7I3c
05wWTfBUO7Sn0TpxTvVT17Y/sx43/UKNDbT+RRLKD55+tsNhiOiygM03YrvplZUx
yoxqWvI8HZ9P7oM9uavS4iZrzKe3dnL5yvLQ0rHG0oMrAd29hpItLCHQWYHfCdT7
n4sAjm2kiQg56IO+7AxLek8Fb4xnW5vsDM+mcmTwFO7U/+6nJL24kUiqqwtwZ6Ab
KKRV8Yz0cxYOhWsUU2LEn87vW89SppYP5a7eL9jbwPCm7YDmzR4Vsdnq2kfEz9Sz
IRxvLuWS/Qx7KJYc2NEinyRvNuGisZAtAktJBBY+lKMBlKq+BgdR5L/2qiBYKdu8
ru1q4nCXa6zc+GQ+OQoM1PskDjQLzHUfU2q8BDGWjAVo8mABTO/YlRdAcgBDSN7u
UUm6zLQabcu/j7PCaPfp0RDO3tJVyfx58UrgYHmwbnm4rhOPvnCPKbHQ6J3Zrs9D
rS2/fzHWROYNCTXKYc7poKTus9im1BQJmsjsRk1BgYzCYBzioHkIG+smynVXdti8
P0ypRfueeGeKTKb6t+jsTQ==
-----END CERTIFICATE-----"""
CFSSL_INTERMEDIATE = """-----BEGIN CERTIFICATE-----
MIIFzjCCA7agAwIBAgIUfn7tEXsiAKGxrw1aoYhJFJKZlU4wDQYJKoZIhvcNAQEN
BQAwbjELMAkGA1UEBhMCREUxDjAMBgNVBAgTBUJhV3VlMRIwEAYDVQQHEwlTdHV0
dGdhcnQxEjAQBgNVBAoTCVNlcmlhbGl6ZTELMAkGA1UECxMCSVQxGjAYBgNVBAMT
EVNlcmlhbGl6ZSBSb290IENBMB4XDTE5MTExMjAzNTkwMFoXDTIwMTExMTAzNTkw
MFowbjELMAkGA1UEBhMCREUxDjAMBgNVBAgTBUJhV3VlMRIwEAYDVQQHEwlTdHV0
dGdhcnQxEjAQBgNVBAoTCVNlcmlhbGl6ZTELMAkGA1UECxMCSVQxGjAYBgNVBAMT
EVNlcmlhbGl6ZSBSb290IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
AgEAwAZLMHuiCGo4D+zLaoeZn1MB/kffUGgGs6znQbXDUa40G5ZkuWVXEQh6vLa2
4NkybOH52Wu325b0ActUHG8bg24S0NLbumYJI7RCqfbw+xwXW+dXuU6bnicK4fez
3Do/nvfJyFgftG+Ykp6e9hUDhWJpz2UL4HKS/cSnxDFKpv6qHUSUCUsADk/3TP82
we/CeCKvsQZW7X8cnMyJ9GOziihQo6+1+78gTphFH3macImT5ak89HXhEx85aCw+
yS3HIg2dY34AkbEP0vUmrdedd007Kwlkbeczzowdegq9DBNhaj31hNLUkw7DXHYx
o1JKsOx9ymq9wYYot1r1VuJPKGpK8VPJUuWfEIFvHUTa9SSlhdL6ZE/gQ0Ej38Ks
LoKqLnAXGrLMgMPO4Sxl/dtemPea6BwRTrzlY+hH2NBH4mO0qWL4NEi7VN3WtOK+
KoWN2d/nnAc+EKdwxsndZpJ9ONxcUTdiZxvFz4jDhM+1xh4uTsNK3pnbxUA4sqcn
+CmqGIYPINpK7G5j8NqZyIe5FBtfr1TwywfFXXtMHiHYIrheT8iva9AgBwOxgiH0
Gvsiq0Nxo34+4Yf8dEavE5g3ddLpvuXzV8298+JG6i1y4EnDH9sNctyFZZVKU4KH
dlhEyua343ex7ySvxJFcluFT6qJyOwtRPMVPFk3vkUjnyV8CAwEAAaNkMGIwDgYD
VR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjASBgNV
HRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBRs+t3cow6JMXbBZnWRN2O/RITH/DAN
BgkqhkiG9w0BAQ0FAAOCAgEAQyb2LWxpIQuJ1kRhug4aELDontHU0F72Ifd0svFd
740Z+nqM/ZwDwxkYnRCFQjQJ9BvKpll9vLl52HEURXRv8B+RZ8NzIoUjcarpPzuk
W5cUiUKqXkxFzPKA3opaWqYDYS741uCBBGwYXSbB2Bn62ct5P0h9BNM0ZwfkX/fR
7tRnJWf6cCUmbr6fPLq4URf/R2TdhaHOOEfeQUxeu5oZBSc/rb/P6Ty6O8k3zWi7
bDkCci8k/WHRUl6olzTm+LzhbvCZ9W4uBiGlYyrkH8v9gex+ve0nxGUuCmWaDD+N
FLU57CyPONbb4oAOGUJ1biipu+gp6MYcWHmzumNmkwNSzI7j+PNlQw8AlN6HVhfL
jOKTcNmLMLrkI61ShLWJJ68H+x3j3YFBIlMz1mpr0/U24Sr3wj+PH0dmqtkmaCDD
a+kso4NKql+P99g10KeLgYUuKPI/t8UbG8LR+bagPWco+lLseIjPXtj2hGn4fj4B
jOsLnBA0F7USvvQd/7BYhh4ck3DkzWzTULM5L9SYcvSFQMbO+r/STj71VaOxu9dx
bUvRfZUMRQHaOOYlahuHiqJqTxrTJiUWAzo/zePuDy3gYN+sEUDlAe7fIfXVEb3e
TASUouTHOKnmX6yOOmMdRF4uidDNaFPylO6hwGXE3G1PqOfO3C7n51QVdd1kB5f8
L/w=
-----END CERTIFICATE-----"""
CFSSL_KEY = ''
